In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/mlt/preprocessing_dataset.csv')
df.head()

      Name   Age Gender   Salary Department
0    Alice  25.0      F  50000.0         HR
1      Bob  30.0      M  60000.0    Finance
2  Charlie   NaN      M  55000.0         IT
3    David  40.0      M  58000.0         HR
4      Eve  22.0      F  52000.0         IT

In [ ]:
df1=df.copy()
df2=df.copy()

In [ ]:
from sklearn.impute import SimpleImputer

imp=SimpleImputer(strategy='mean')
df['Age']=imp.fit_transform(df[['Age']])
df['Salary']=imp.fit_transform(df[['Salary']])
imp1=SimpleImputer(strategy='most_frequent')
df[['Gender']]=imp1.fit_transform(df[['Gender']])

**LABEL ENCODING**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender_encoded']=le.fit_transform(df['Gender'])
df

      Name         Age Gender        Salary Department  Gender_encoded
0    Alice   25.000000      F  50000.000000         HR               0
1      Bob   30.000000      M  60000.000000    Finance               1
2  Charlie   39.555556      M  55000.000000         IT               1
3    David   40.000000      M  58000.000000         HR               1
4      Eve   22.000000      F  52000.000000         IT               0
5    Frank   35.000000      M  61000.000000    Finance               1
6    Grace  120.000000      F  57777.777778    Finance               0
7    Henry   28.000000      M  59000.000000         HR               1
8      Ivy   29.000000      F  63000.000000         IT               0
9     Jack   27.000000      M  62000.000000    Finance               1

**ONE HOT ENCODING**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

one=OneHotEncoder(sparse_output=False)
df1['Gender']=one.fit_transform(df1[['Gender']])
df1

      Name    Age  Gender   Salary Department
0    Alice   25.0     1.0  50000.0         HR
1      Bob   30.0     0.0  60000.0    Finance
2  Charlie    NaN     0.0  55000.0         IT
3    David   40.0     0.0  58000.0         HR
4      Eve   22.0     1.0  52000.0         IT
5    Frank   35.0     0.0  61000.0    Finance
6    Grace  120.0     1.0      NaN    Finance
7    Henry   28.0     0.0  59000.0         HR
8      Ivy   29.0     1.0  63000.0         IT
9     Jack   27.0     0.0  62000.0    Finance

In [ ]:
df2=pd.get_dummies(df2,columns=['Gender'],drop_first=True)
df2

      Name    Age   Salary Department  Gender_M
0    Alice   25.0  50000.0         HR     False
1      Bob   30.0  60000.0    Finance      True
2  Charlie    NaN  55000.0         IT      True
3    David   40.0  58000.0         HR      True
4      Eve   22.0  52000.0         IT     False
5    Frank   35.0  61000.0    Finance     False
6    Grace  120.0      NaN    Finance     False
7    Henry   28.0  59000.0         HR      True
8      Ivy   29.0  63000.0         IT     False
9     Jack   27.0  62000.0    Finance      True